### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by deed02392**
* Add a section on how to configure W:A clients.
* Change archive download format to gzipped tar - zip is not included by default on common platforms such as Debian but gzip nearly always is.

### CODE REVIEW

**Comment by CyberShadow** [comment]
> Add a section on how to configure W:A clients.

Thanks, applied.

> Change archive download format to gzipped tar - zip is not included by default on common platforms such as Debian but gzip nearly always is.

Not sure about that one. The reason why the documentation uses `.zip` is because it is available out-of-the-box on Windows. Of the two formats, ZIP is most likely to be supported by any OS.

**Comment by deed02392** [comment]
Hmm I did not consider Windows support since the command-line instructions were using other utilities like `wget`, `mv`, `rm` etc..

How about we put a comment after each line using `.zip` to let users know that `.tar.gz` is also available at a similar URI, so people don't think they are forced to install a particular archive utility?

**Comment by CyberShadow** [comment]
Honestly, it seems like too much.

The canonical way to install software from GitHub is to use git; and the canonical way to install software written in a programming language is to use that language's package manager. In the latest version of the README I've added instructions for the latter, and emphasized that the manual method with downloading and unpacking archives is not recommended (and probably should be removed entirely), because it makes updates too complicated.

**Comment by deed02392** [comment]
Agreed, I think with the addition of the package release, we do not need to make such provisions for the much less recommended method of manually downloading archived versions.

**Pull request closed without merging**
